FROM jz_ai_model_img:gpu_v1

# Set environment variables

# Clean apt cache
RUN apt-get update && apt-get install ffmpeg -y
RUN apt-get clean && rm -rf /var/lib/apt/lists/*

# Set working directory and clone repository

# Install dependencies
COPY requirements.txt .
RUN pip install -r requirements.txt -i https://mirrors.aliyun.com/pypi/simple/

EXPOSE 8501

CMD ["streamlit", "run", "st.py"]
